project_id = "qykxikvizhzeqdsbcapt"

[functions.process-receipt]
verify_jwt = false

[functions.reconcile-banks]
verify_jwt = false

[functions.budget-watch]
verify_jwt = false

[functions.logistics-metrics]
verify_jwt = false

[functions.restaurant-prime-cost]
verify_jwt = false

[functions.retail-margins]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false
